// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESpgauge

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RMPgauge = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_RMPgauge, 220);
    lv_obj_set_height(ui_RMPgauge, 220);
    lv_obj_set_align(ui_RMPgauge, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_RMPgauge, 0, 8000);
    lv_arc_set_value(ui_RMPgauge, 8000);
    lv_arc_set_bg_angles(ui_RMPgauge, 100, 260);
    lv_obj_set_style_arc_color(ui_RMPgauge, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RMPgauge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_RMPgauge, lv_color_hex(0x9C10A1), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RMPgauge, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RMPgauge, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RMPgauge, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SpeedGauge = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedGauge, 220);
    lv_obj_set_height(ui_SpeedGauge, 220);
    lv_obj_set_align(ui_SpeedGauge, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_SpeedGauge, LV_STATE_CHECKED);       /// States
    lv_arc_set_range(ui_SpeedGauge, 0, 160);
    lv_arc_set_value(ui_SpeedGauge, 160);
    lv_arc_set_bg_angles(ui_SpeedGauge, 280, 80);
    lv_arc_set_mode(ui_SpeedGauge, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_color(ui_SpeedGauge, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpeedGauge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedGauge, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedGauge, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SpeedLable = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLable, 43);
    lv_obj_set_y(ui_SpeedLable, 3);
    lv_obj_set_align(ui_SpeedLable, LV_ALIGN_CENTER);

    ui_RPMLable = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RPMLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMLable, -59);
    lv_obj_set_y(ui_RPMLable, 3);
    lv_obj_set_align(ui_RPMLable, LV_ALIGN_CENTER);

    ui_RPMunit = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RPMunit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMunit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMunit, -39);
    lv_obj_set_y(ui_RPMunit, 21);
    lv_obj_set_align(ui_RPMunit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPMunit, "RPM");

    ui_SpeedUnit = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedUnit, 55);
    lv_obj_set_y(ui_SpeedUnit, 19);
    lv_obj_set_align(ui_SpeedUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedUnit, "km/h");

    ui_yellowBatWarrinig = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yellowBatWarrinig, &ui_img_path25_png);
    lv_obj_set_width(ui_yellowBatWarrinig, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_yellowBatWarrinig, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_yellowBatWarrinig, -43);
    lv_obj_set_y(ui_yellowBatWarrinig, -36);
    lv_obj_set_align(ui_yellowBatWarrinig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yellowBatWarrinig, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yellowBatWarrinig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_yellowBatWarrinig, 180);

    ui_redBatWarring = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_redBatWarring, &ui_img_path19_png);
    lv_obj_set_width(ui_redBatWarring, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_redBatWarring, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_redBatWarring, -43);
    lv_obj_set_y(ui_redBatWarring, -36);
    lv_obj_set_align(ui_redBatWarring, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_redBatWarring, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_redBatWarring, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_redBatWarring, 180);

    ui_yellowOilWarrning = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yellowOilWarrning, &ui_img_path15_png);
    lv_obj_set_width(ui_yellowOilWarrning, LV_SIZE_CONTENT);   /// 47
    lv_obj_set_height(ui_yellowOilWarrning, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_yellowOilWarrning, 40);
    lv_obj_set_y(ui_yellowOilWarrning, -36);
    lv_obj_set_align(ui_yellowOilWarrning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yellowOilWarrning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yellowOilWarrning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_redOilWarring = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_redOilWarring, &ui_img_2122316114);
    lv_obj_set_width(ui_redOilWarring, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_redOilWarring, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_redOilWarring, 41);
    lv_obj_set_y(ui_redOilWarring, -36);
    lv_obj_set_align(ui_redOilWarring, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_redOilWarring, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_redOilWarring, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yellowEngineWarrning = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_yellowEngineWarrning, &ui_img_image1_png);
    lv_obj_set_width(ui_yellowEngineWarrning, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_yellowEngineWarrning, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_yellowEngineWarrning, -3);
    lv_obj_set_y(ui_yellowEngineWarrning, 63);
    lv_obj_set_align(ui_yellowEngineWarrning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yellowEngineWarrning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_yellowEngineWarrning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_redEngineWarrning = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_redEngineWarrning, &ui_img_path17_png);
    lv_obj_set_width(ui_redEngineWarrning, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_redEngineWarrning, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_redEngineWarrning, -3);
    lv_obj_set_y(ui_redEngineWarrning, 65);
    lv_obj_set_align(ui_redEngineWarrning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_redEngineWarrning, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_redEngineWarrning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
